### ISSUE TITLE
getAgeR (cgageR) Error in df[cgi, i] : subscript out of bounds

### ISSUE THREAD

**Issue by Rantanflan** [metamaden/cgageR#1]
I am trying to use the getAgeR function from cgageR. I started by trying to reproduce the example provided in (https://rdrr.io/github/metamaden/cgageR/man/getAgeR.html) but I am getting the same error message all the time. 

library("cgageR")
library("wateRmelon")
data(melon)
bval <- betas(melon)
est.ages <- getAgeR(bval,epitoc=TRUE,horvath=TRUE,hannum=TRUE,drift=FALSE,showStatusHannum=TRUE,
                    keepcpgs.epitoc=TRUE,keepcpgs.hannum=TRUE,keepres=FALSE,chrage=NULL)

I am trying to use the getAgeR function from cgageR. I started by trying to reproduce the example provided in the description but I am getting the same error message all the time. Has anyone experience with getAgeR and has been able to run it?

    library("cgageR")
    library("wateRmelon")
    
    data(melon)
    bval <- betas(melon)
    
    est.ages <- getAgeR(bval,epitoc=TRUE,horvath=TRUE,hannum=TRUE,drift=FALSE,showStatusHannum=TRUE,
                    keepcpgs.epitoc=TRUE,keepcpgs.hannum=TRUE,keepres=FALSE,chrage=NULL)

I get:

    Getting epiTOC age estimates...
    Number of available epiTOC CpGs: 2/385.
    Done! Continuing...
    Getting Horvath age estimates...
    No coefficients detected, using Horvaths clock
    Done! Continuing...
    Initializing Hannum Clock age estimates...
    Error in df[cgi, i] : subscript out of bounds

Any idea of what I am doing wrong? Thanks

**Comment by metamaden** [comment]
Hello, and thanks for your interest in this project! 

No, I don't think you're doing anything wrong. It looks like the `getHannum` function being called by `getAgeR` needs better error handling, e.g. in the case where none of the coefficients are detected. I've started work on this in a new branch, which I will merge with the main when it's ready. 

In the meantime, I'll just draw your attention to the `methylclock` package, which was published this year and looks like it is being updated more frequently: https://github.com/isglobal-brge/methylclock

**Comment by Rantanflan** [comment]
Thank you very much for the reply.

I will have a look to the package that you recommend.

all the best,

Jose

________________________________
De: Sean Maden <notifications@github.com>
Enviado: martes, 13 de octubre de 2020 21:26
Para: metamaden/cgageR <cgageR@noreply.github.com>
Cc: Rantanflan <rantanflan@hotmail.com>; Author <author@noreply.github.com>
Asunto: Re: [metamaden/cgageR] getAgeR (cgageR) Error in df[cgi, i] : subscript out of bounds (#1)


Hello, and thanks for your interest in this project!

No, I don't think you're doing anything wrong. It looks like the getHannum function being called by getAgeR needs better error handling, e.g. in the case where none of the coefficients are detected. I've started work on this in a new branch, which I will merge with the main when it's ready.

In the meantime, I'll just draw your attention to the methylclock package, which was published this year and looks like it is being updated more frequently: https://github.com/isglobal-brge/methylclock
